# Generated by Django 5.2.3 on 2025-06-24 14:10

from django.db import migrations
import datetime

def populate_services(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Service = apps.get_model('services', 'Service')

    # Create Hairdressers
    hairdresser1 = User.objects.create_user(
        username='jessica', 
        password='password', 
        first_name='Jessica', 
        last_name='Jones',
        email='jessica@example.com',
        role='hairdresser'
    )
    hairdresser2 = User.objects.create_user(
        username='mike', 
        password='password', 
        first_name='Mike', 
        last_name='Miller',
        email='mike@example.com',
        role='hairdresser'
    )

    # Create Services
    Service.objects.create(
        name='Men\'s Haircut', 
        duration=datetime.timedelta(minutes=30), 
        price=25.00, 
        hairdresser=hairdresser1
    )
    Service.objects.create(
        name='Women\'s Haircut', 
        duration=datetime.timedelta(hours=1), 
        price=45.00, 
        hairdresser=hairdresser1
    )
    Service.objects.create(
        name='Beard Trim', 
        duration=datetime.timedelta(minutes=15), 
        price=15.00, 
        hairdresser=hairdresser2
    )
    Service.objects.create(
        name='Hair Coloring', 
        duration=datetime.timedelta(hours=2), 
        price=75.00, 
        hairdresser=hairdresser2
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_services),
    ]
