# Generated by Django 5.2.3 on 2025-06-24 16:09

from django.db import migrations
import datetime

def populate_services(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Service = apps.get_model('services', 'Service')

    # Create Hairdressers
    hairdresser1 = User.objects.create_user(
        username='karim', 
        password='password', 
        first_name='Karim', 
        last_name='Lazaar',
        email='karim@example.com',
        role='hairdresser'
    )
    hairdresser2 = User.objects.create_user(
        username='fatima', 
        password='password', 
        first_name='Fatima', 
        last_name='Zahra',
        email='fatima@example.com',
        role='hairdresser'
    )

    # Create Services
    Service.objects.create(
        name='Coupe homme', 
        duration=datetime.timedelta(minutes=45), 
        price=80.00, 
        hairdresser=hairdresser1
    )
    Service.objects.create(
        name='Soin de barbe', 
        duration=datetime.timedelta(minutes=20), 
        price=50.00, 
        hairdresser=hairdresser1
    )
    Service.objects.create(
        name='Lissage Protéine', 
        duration=datetime.timedelta(hours=2, minutes=30), 
        price=450.00, 
        hairdresser=hairdresser2
    )
    Service.objects.create(
        name='Teinture', 
        duration=datetime.timedelta(hours=1, minutes=30), 
        price=250.00, 
        hairdresser=hairdresser2
    )

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_services),
    ]
